import "./globals.css";

export const metadata = {
  title: "Paw Pets App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" bg-[#FFF9F5]" suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
